// options
export const REQUEST_OPTIONS = 'REQUEST_OPTIONS'
export const RECEIVE_OPTIONS = 'RECEIVE_OPTIONS'

// loading
export const SET_LOADING_VALUE = 'SET_LOADING_VALUE'

// layout
export const SET_LAYOUT_STYLE = 'SET_LAYOUT_STYLE'
export const SET_LAYOUT_BACK_PROP = 'SET_LAYOUT_BACK_PROP'
export const RESET_LAYOUT_BACK_PROP = 'RESET_LAYOUT_BACK_PROP'

// bounds
export const SET_BOUNDS_ELEMENT = 'SET_BOUNDS_ELEMENT'

// form
export const REQUEST_FORM = 'REQUEST_FORM'
export const RECEIVE_FORM = 'RECEIVE_FORM'
export const SEND_CONTACT_FORM = 'SEND_CONTACT_FORM'
export const SENDED_CONTACT_FORM = 'SENDED_CONTACT_FORM'

// nav
export const REQUEST_NAV = 'REQUEST_NAV'
export const RECEIVE_NAV = 'RECEIVE_NAV'

// layer
export const OPEN_LAYER = 'OPEN_LAYER'
export const CLOSE_LAYER = 'CLOSE_LAYER'
export const CLOSE_ALL_LAYER = 'CLOSE_ALL_LAYER'

// content
export const REQUEST_PAGE = 'REQUEST_PAGE'
export const RECEIVE_PAGE = 'RECEIVE_PAGE'

export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const REQUEST_POST = 'REQUEST_POST'
export const RECEIVE_POST = 'RECEIVE_POST'
export const RESET_CURRENT_POST = 'RESET_CURRENT_POST'
export const REQUEST_TAXONOMY = 'REQUEST_TAXONOMY'
export const RECEIVE_TAXONOMY = 'RECEIVE_TAXONOMY'
export const REQUEST_CATEGORY = 'REQUEST_CATEGORY'
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY'

export const REQUEST_CPTS = 'REQUEST_CPTS'
export const RECEIVE_CPTS = 'RECEIVE_CPTS'
export const REQUEST_CPT = 'REQUEST_CPT'
export const RECEIVE_CPT = 'RECEIVE_CPT'
export const RESET_CURRENT_CPT = 'RESET_CURRENT_CPT'

// locale
export const REQUEST_LOCALES = 'REQUEST_LOCALES'
export const RECEIVE_LOCALES = 'RECEIVE_LOCALES'
export const SET_LANGUAGE = 'SET_LANGUAGE'

// Fake Router
export const FAKEROUTER_CHANGE_LOCATION = 'FAKEROUTER_CHANGE_LOCATION'
export const FAKEROUTER_MOVE_FORWARD = 'FAKEROUTER_MOVE_FORWARD'
export const FAKEROUTER_MOVE_BACKWARD = 'FAKEROUTER_MOVE_BACKWARD'
export const FAKEROUTER_RESET = 'FAKEROUTER_RESET'

// user
export const SET_USER_DATA = 'SET_USER_DATA'
export const SET_UA_BROWSER = 'SET_UA_BROWSER'
export const SET_UA_OS = 'SET_UA_OS'
export const SET_VIDEO_SUBMITTED = 'SET_VIDEO_SUBMITTED'
export const TOGGLE_AUDIO = 'TOGGLE_AUDIO'
export const REQUEST_VIDEO = 'REQUEST_VIDEO'
export const RECEIVE_JOB_ID = 'RECEIVE_JOB_ID'
export const REQUEST_VIDEO_STATUS = 'REQUEST_VIDEO_STATUS'
export const RECEIVE_VIDEO_STATUS = 'RECEIVE_VIDEO_STATUS'
export const REQUEST_DOWNLOAD_VIDEO = 'REQUEST_DOWNLOAD_VIDEO'
export const RESET_EXPERIENCE = 'RESET_EXPERIENCE'

// Custom Types
